from .network import NeuralNetworkPyTorch
from .recurrent_network import RecurrentNeuralNetworkPyTorch
from .generative_adversial_network import GenerativeAdversialNetwork
from .utils import maybeCuda, maybeCpu